/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  PedestrianRouteRequest,
  ProcessingMultiResult,
  ProcessingResult
} from '../../schemas'
import { customInstance } from '../../custom-instance';
import type { BodyType } from '../../custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  /**
 * # 보행자 경로 안내 API (단일 버전)

보행자 경로 안내 API를 호출하여 경로 정보를 반환하는 함수입니다.

https://openapi.sk.com/products/detail?svcSeq=4&menuSeq=45
 * @summary Get Single Pedestrian Route
 */
export const getSinglePedestrianRoutePedestrianSinglePost = (
    pedestrianRouteRequest: BodyType<PedestrianRouteRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<ProcessingResult>(
      {url: `/pedestrian/single`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pedestrianRouteRequest
    },
      options);
    }
  /**
 * # 보행자 경로 안내 API (다중 버전)

보행자 경로 안내 API를 호출하여 경로 정보를 반환하는 함수입니다.

총 3개의 경로를 반환합니다.

https://openapi.sk.com/products/detail?svcSeq=4&menuSeq=45
 * @summary Get Multi Pedestrian Route
 */
export const getMultiPedestrianRoutePedestrianMultiPost = (
    pedestrianRouteRequest: BodyType<PedestrianRouteRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<ProcessingMultiResult>(
      {url: `/pedestrian/multi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pedestrianRouteRequest
    },
      options);
    }
  export type GetSinglePedestrianRoutePedestrianSinglePostResult = NonNullable<Awaited<ReturnType<typeof getSinglePedestrianRoutePedestrianSinglePost>>>
export type GetMultiPedestrianRoutePedestrianMultiPostResult = NonNullable<Awaited<ReturnType<typeof getMultiPedestrianRoutePedestrianMultiPost>>>
