/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetNearbyPointsLocationPointGetParams,
  PointWithDistance
} from '../../schemas'
import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  /**
 * # 주변 포인트 조회 API

주변 포인트 정보를 조회하는 함수입니다.
 * @summary Get Nearby Points
 */
export const getNearbyPointsLocationPointGet = (
    params: GetNearbyPointsLocationPointGetParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<PointWithDistance[]>(
      {url: `/location/point`, method: 'GET',
        params
    },
      options);
    }
  export type GetNearbyPointsLocationPointGetResult = NonNullable<Awaited<ReturnType<typeof getNearbyPointsLocationPointGet>>>
