/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  PoiResponse,
  SearchPoiPoiSearchGetParams
} from '../../schemas'
import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  /**
 * # 장소(POI) 검색 API

Tmap POI 검색 API를 사용하여 장소를 검색합니다.

https://openapi.sk.com/products/detail?linkMenuSeq=12#Querystring_Parameters
 * @summary Search Poi
 */
export const searchPoiPoiSearchGet = (
    params: SearchPoiPoiSearchGetParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<PoiResponse>(
      {url: `/poi/search`, method: 'GET',
        params
    },
      options);
    }
  export type SearchPoiPoiSearchGetResult = NonNullable<Awaited<ReturnType<typeof searchPoiPoiSearchGet>>>
