/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { EvCharger } from './evCharger';

export interface EvChargers {
  /** 충전기 목록 */
  evCharger: EvCharger[];
}
