/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GroupSubSubCenterX } from './groupSubSubCenterX';
import type { GroupSubSubCenterY } from './groupSubSubCenterY';
import type { GroupSubSubClassCd } from './groupSubSubClassCd';
import type { GroupSubSubClassNmA } from './groupSubSubClassNmA';
import type { GroupSubSubClassNmB } from './groupSubSubClassNmB';
import type { GroupSubSubClassNmC } from './groupSubSubClassNmC';
import type { GroupSubSubClassNmD } from './groupSubSubClassNmD';
import type { GroupSubSubName } from './groupSubSubName';
import type { GroupSubSubNavSeq } from './groupSubSubNavSeq';
import type { GroupSubSubNavX } from './groupSubSubNavX';
import type { GroupSubSubNavY } from './groupSubSubNavY';
import type { GroupSubSubParkYn } from './groupSubSubParkYn';
import type { GroupSubSubPkey } from './groupSubSubPkey';
import type { GroupSubSubPoiId } from './groupSubSubPoiId';
import type { GroupSubSubRpFlag } from './groupSubSubRpFlag';
import type { GroupSubSubSeq } from './groupSubSubSeq';

export interface GroupSub {
  /** 부속 시설물의 중심 X 좌표 */
  subCenterX?: GroupSubSubCenterX;
  /** 부속 시설물의 중심 Y 좌표 */
  subCenterY?: GroupSubSubCenterY;
  /** 부속 시설물의 업종 코드 */
  subClassCd?: GroupSubSubClassCd;
  /** 부속 시설물의 업종 대분류명 */
  subClassNmA?: GroupSubSubClassNmA;
  /** 부속 시설물의 업종 중분류명 */
  subClassNmB?: GroupSubSubClassNmB;
  /** 부속 시설물의 업종 소분류명 */
  subClassNmC?: GroupSubSubClassNmC;
  /** 부속 시설물의 업종 세분류명 */
  subClassNmD?: GroupSubSubClassNmD;
  /** 부속 시설물의 명칭 */
  subName?: GroupSubSubName;
  /** 부속 시설물의 입구 번호 */
  subNavSeq?: GroupSubSubNavSeq;
  /** 부속 시설물의 입구 X 좌표 */
  subNavX?: GroupSubSubNavX;
  /** 부속 시설물의 입구 Y 좌표 */
  subNavY?: GroupSubSubNavY;
  /** 부속 시설물의 주차 여부 */
  subParkYn?: GroupSubSubParkYn;
  /** 관심 장소(POI) 식별자 */
  subPkey?: GroupSubSubPkey;
  /** 부속 시설물의 관심 장소(POI) ID */
  subPoiId?: GroupSubSubPoiId;
  /** 부속 시설물의 길안내 요청에 필요한 값 */
  subRpFlag?: GroupSubSubRpFlag;
  /** 부속 시설물의 일련번호 */
  subSeq?: GroupSubSubSeq;
}
