/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GroupSub } from './groupSub';

export interface GroupSubs {
  /** 검색한 관심 장소(POI)의 그룹 하위 목록 */
  groupSub?: GroupSub[];
}
