/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NewAddressBldNo1 } from './newAddressBldNo1';
import type { NewAddressBldNo2 } from './newAddressBldNo2';
import type { NewAddressCenterLat } from './newAddressCenterLat';
import type { NewAddressCenterLon } from './newAddressCenterLon';
import type { NewAddressFrontLat } from './newAddressFrontLat';
import type { NewAddressFrontLon } from './newAddressFrontLon';
import type { NewAddressFullAddressRoad } from './newAddressFullAddressRoad';
import type { NewAddressRoadId } from './newAddressRoadId';
import type { NewAddressRoadName } from './newAddressRoadName';

export interface NewAddress {
  /** 건물번호의 본번 */
  bldNo1?: NewAddressBldNo1;
  /** 건물번호의 부번 */
  bldNo2?: NewAddressBldNo2;
  /** 중심점 위도 좌표 */
  centerLat?: NewAddressCenterLat;
  /** 중심점 경도 좌표 */
  centerLon?: NewAddressCenterLon;
  /** 장소(시설물) 입구 위도 좌표 */
  frontLat?: NewAddressFrontLat;
  /** 장소(시설물) 입구 경도 좌표 */
  frontLon?: NewAddressFrontLon;
  /** 전체 도로명 주소 */
  fullAddressRoad?: NewAddressFullAddressRoad;
  /** 도로명 코드 */
  roadId?: NewAddressRoadId;
  /** 도로명 */
  roadName?: NewAddressRoadName;
}
