/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NewAddress } from './newAddress';

export interface NewAddresses {
  /** 새주소 목록 */
  newAddress?: NewAddress[];
}
