/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * 보행자 경로 안내 응답의 Feature Properties 정보를 담는 DTO입니다.
 */
export interface PedestrianRouteResponseFeatureProperties {
  /** 길 안내 정보 */
  description?: string;
  /** 방면 명칭 */
  direction?: string;
  /** 시설물 명칭 */
  facilityName?: string;
  /** 시설물 유형 (1: 교량, 2: 터널, 3: 고가도로, 11: 일반보행자도로, 12: 육교, 14: 지하보도, 15: 횡단보도, 16: 대형시설물이동통로, 17: 계단) */
  facilityType?: string;
  /** 경로 순번 */
  index: number;
  /** 교차로 명칭 */
  intersectionName?: string;
  /** 안내 지점 명칭 */
  name?: string;
  /** 안내 지점 주변 POI 명칭 */
  nearPoiName?: string;
  /** 안내 지점 주변 POI X 좌표 */
  nearPoiX?: number;
  /** 안내 지점 주변 POI Y 좌표 */
  nearPoiY?: number;
  /** 아이콘 노드 */
  pointIndex?: number;
  /** 안내 지점 유형 (SP: 출발지, EP: 도착지, PP: 경유지, GP: 일반 안내점) */
  pointType?: string;
  /** 경로 총 거리 (m) */
  totalDistance?: number;
  /** 경로 총 소요시간 (초) */
  totalTime?: number;
  /** 회전 정보 (11: 직진, 12: 좌회전, 13: 우회전, 14: 유턴) */
  turnType?: number;
}
