/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * 보행자 경로 안내 응답의 Feature Geometry 정보를 담는 DTO입니다.
 */
export interface PedestrianRouteResponseFeatureGeometry {
  /** 좌표 정보 ([[x1, y1], [x2, y2]], Point에서는 [x, y]) */
  coordinates: unknown[];
  /** Geometry 유형 (Point, LineString) */
  type: string;
}
