/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PedestrianRouteResponseFeatureGeometry } from './pedestrianRouteResponseFeatureGeometry';
import type { PedestrianRouteResponseFeatureProperties } from './pedestrianRouteResponseFeatureProperties';

/**
 * 보행자 경로 안내 응답의 Feature 정보를 담는 DTO입니다.
 */
export interface PedestrianRouteResponseFeature {
  geometry: PedestrianRouteResponseFeatureGeometry;
  properties: PedestrianRouteResponseFeatureProperties;
  /** Feature 유형 */
  type: string;
}
