/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GroupSubs } from './groupSubs';

/**
 * 검색한 관심 장소(POI)의 그룹 하위 목록
 */
export type PoiGroupSubLists = GroupSubs | null;
