/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NewAddresses } from './newAddresses';

/**
 * 새주소 목록
 */
export type PoiNewAddressList = NewAddresses | null;
