/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * road 데이터의 Point 정보와 거리 정보를 담는 DTO입니다.
 */
export interface PointWithDistance {
  /** Distance (km) */
  distance: number;
  /** Duration in seconds */
  duration?: number;
  /** Elevation */
  ele?: number;
  /** Point ID */
  id?: string;
  /** Latitude */
  lat: number;
  /** Longitude */
  lng: number;
  /** Speed in m/s */
  speed?: number;
  /** Timestamp */
  time?: string;
  /** Path to video file */
  video?: string;
}
