/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PoiResponseSearchPoiInfo } from './poiResponseSearchPoiInfo';

export interface PoiResponse {
  /** 관심 장소(POI)를 검색한 결과의 정보 */
  searchPoiInfo?: PoiResponseSearchPoiInfo;
}
