/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SearchPoiInfo } from './searchPoiInfo';

/**
 * 관심 장소(POI)를 검색한 결과의 정보
 */
export type PoiResponseSearchPoiInfo = SearchPoiInfo | null;
