/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Poi } from './poi';

export interface Pois {
  /** 검색 결과의 관심 장소(POI) 정보 */
  poi: Poi[];
}
