/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProcessingResult } from './processingResult';

export interface ProcessingMultiResult {
  /** Boulevard route (대로 우선) */
  boulevard: ProcessingResult;
  /** Shortest route (최단 + 계단 제외 경로) */
  shortest: ProcessingResult;
  /** Suggestion route (추천 경로) */
  suggestion: ProcessingResult;
}
