/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Pois } from './pois';

/**
 * 관심 장소(POI) 목록
 */
export type SearchPoiInfoPois = Pois | null;
