/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SearchPoiPoiSearchGetParams = {
version?: number;
searchKeyword: string;
searchType?: string | null;
areaLLCode?: string | null;
areaLMCode?: string | null;
reqCoordType?: string | null;
resCoordType?: string | null;
searchtypCd?: string | null;
centerLon?: number | null;
centerLat?: number | null;
radius?: number | null;
page?: number;
count?: number;
multiPoint?: string | null;
poiGroupYn?: string | null;
};
